routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$importants = DB::table('packages')->where('outstanding','1')->get();
	$packages = DB::table('packages')->paginate(6);
    return view('welcome',compact('packages','importants'));
})->name('index');

Route::get('packs','PacksController@store')->name('packs');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('hotels','HotelController');

Route::resource('airlines','AirlineController');

Route::resource('services','ServiceController');

Route::resource('packages','PackageController');

Route::resource('catalogs','CatalogController');

Route::resource('categories','CategoryPackageController');

Route::resource('users','UserController');

resources/views/admin/airlineForm.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de Aerolinea') }}</div>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('airlines.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="airline_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre de la Aerolinea') }}</label>

                            <div class="col-md-6">
                                <input id="airline_name" type="text" class="form-control{{ $errors->has('airline_name') ? ' is-invalid' : '' }}" name="airline_name" value="{{ old('airline_name') }}" required autofocus>

                                @if ($errors->has('airline_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('airline_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


  						<div class="form-group row">
                            <label for="airline_photo" class="col-md-4 col-form-label text-md-right">{{ __('Foto de la Aerolinea') }}</label>

                            <div class="col-md-6">
                                <input type="file" id="airline_photo" type="text" class="form-control" name="airline_photo" required>
                            </div>
                        </div>

						<div class="form-group row">
                            <label for="airline_webpage" class="col-md-4 col-form-label text-md-right">{{ __('Pagina Web') }}</label>

                            <div class="col-md-6">
                                <input id="airline_webpage" type="text" class="form-control" name="airline_webpage" required>
                            </div>
                        </div>


                    <div class="form-group row">
                            <label for="round_flidht" class="col-md-4 col-form-label text-md-right">{{ __('Vuelo redondo') }}</label>

                            <div class="col-md-6">
                            <select id="round_flidht" type="text" class="form-control" name="round_flidht" >
                                <option value="1">Si</option>
                                <option value="0">No</option>
                            </select>
                            </div>
                        </div>




             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/catalogEdit.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de Catalogo') }}</div>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('catalogs.update',$catalog->id) }}">
                       
                              {!! csrf_field() !!}
          {!! method_field('PUT') !!}

                        <div class="form-group row">
                            <label for="catalog_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del Catalogo') }}</label>

                            <div class="col-md-6">
                                <input id="catalog_name" type="text" class="form-control{{ $errors->has('catalog_name') ? ' is-invalid' : '' }}" name="catalog_name" value="{{ $catalog->catalog_name}}" required autofocus>

                                @if ($errors->has('catalog_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('catalog_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


  						<div class="form-group row">
                            <label for="catalog_image" class="col-md-4 col-form-label text-md-right">{{ __('Foto del Catalogo') }}</label>

                            <div class="col-md-6">
                                <input type="file" id="catalog_image" type="text" class="form-control" name="catalog_image">
                            </div>
                        </div>

						


             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Actualizar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/catalogForm.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de Catalogo') }}</div>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('catalogs.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="catalog_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del Catalogo') }}</label>

                            <div class="col-md-6">
                                <input id="catalog_name" type="text" class="form-control{{ $errors->has('catalog_name') ? ' is-invalid' : '' }}" name="catalog_name" value="{{ old('catalog_name') }}" required autofocus>

                                @if ($errors->has('catalog_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('catalog_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


  						<div class="form-group row">
                            <label for="catalog_image" class="col-md-4 col-form-label text-md-right">{{ __('Foto del Catalogo') }}</label>

                            <div class="col-md-6">
                                <input type="file" id="catalog_image" type="text" class="form-control" name="catalog_image" required>
                            </div>
                        </div>

						


             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categoryEdit.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Actualizacion de Catalogo') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('categories.update',$category->id) }}">
                                {!! csrf_field() !!}
          {!! method_field('PUT') !!}

                        <div class="form-group row">
                            <label for="category_pack_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre de la Categoria') }}</label>

                            <div class="col-md-6">
                                <input id="category_pack_name" type="text" class="form-control{{ $errors->has('category_pack_name') ? ' is-invalid' : '' }}" name="category_pack_name" value="{{$category->category_pack_name}}" required autofocus>

                                @if ($errors->has('category_pack_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('category_pack_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>



						


             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categoryForm.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de Catalogo') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('categories.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="category_pack_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre de la Categoria') }}</label>

                            <div class="col-md-6">
                                <input id="category_pack_name" type="text" class="form-control{{ $errors->has('category_pack_name') ? ' is-invalid' : '' }}" name="category_pack_name" value="{{ old('category_pack_name') }}" required autofocus>

                                @if ($errors->has('category_pack_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('category_pack_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>



						


             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/hotelForm.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de Hotel') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('hotels.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="hotel_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del hotel') }}</label>

                            <div class="col-md-6">
                                <input id="hotel_name" type="text" class="form-control{{ $errors->has('hotel_name') ? ' is-invalid' : '' }}" name="hotel_name" value="{{ old('hotel_name') }}" required autofocus>

                                @if ($errors->has('hotel_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('hotel_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


  						<div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Dirección') }}</label>

                            <div class="col-md-6">
                                <input id="hotel_address" type="text" class="form-control" name="hotel_address" required>
                            </div>
                        </div>

						<div class="form-group row">
                            <label for="web_page" class="col-md-4 col-form-label text-md-right">{{ __('Pagina Web') }}</label>

                            <div class="col-md-6">
                                <input id="web_page" type="text" class="form-control" name="web_page" required>
                            </div>
                        </div>


             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/indexAirlines.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
    <div class="row justify-content-center">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Vuelo redondo</th>
      <th scope="col">Pagina web</th>
      <th scope="col">Foto</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($airlines as $airline)

    <tr>
      <td>{{$airline->airline_name}}</td>
@if($airline->round_flidht==1)
      <td>Si</td>
@else

  <td>No</td>
@endif
      <td>{{$airline->airline_webpage}}</td>

      <td><img src="/montpellier/storage/app/{{($airline->airline_photo)}}"></td>


    <td>
        <a class="btn btn-info btn-xs" href="{{route('airlines.edit',$airline->id)}}">Editar</a>

        <form style="display:inline" method="POST" action="{{route('airlines.destroy',$airline->id)}}">
          {!! csrf_field() !!}
          {!! method_field('DELETE') !!}
          
          <button class="btn btn-danger" type="submit">Eliminar</button>


        </form>
      </td>


     
    </tr>

    @endforeach
</tbody>
</table>
</div>
</div>
@endsection

resources/views/admin/indexCatalogs.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
    <div class="row justify-content-center">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Foto</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($catalogs as $catalog)

    <tr>
      <td>{{$catalog->catalog_name}}</td>


      <td><img src="/montpellier/storage/app/{{($catalog->catalog_image)}}"></td>


    <td>
        <a class="btn btn-info btn-xs" href="{{route('catalogs.edit',$catalog->id)}}">Editar</a>

        <form style="display:inline" method="POST" action="{{route('catalogs.destroy',$catalog->id)}}">
          {!! csrf_field() !!}
          {!! method_field('DELETE') !!}
          
          <button class="btn btn-danger" type="submit">Eliminar</button>


        </form>
      </td>


     
    </tr>

    @endforeach
</tbody>
</table>
</div>
</div>
@endsection

resources/views/admin/indexCategories.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>

      <th scope="col">Acciones</th>
      
    </tr>
  </thead>
  <tbody>
  	@foreach($categories as $category)

    <tr>
      <td>{{$category->category_pack_name}}</td>
     

          <td>
        <a class="btn btn-info btn-xs" href="{{route('categories.edit',$category->id)}}">Editar</a>

        <form style="display:inline" method="POST" action="{{route('categories.destroy',$category->id)}}">
          {!! csrf_field() !!}
          {!! method_field('DELETE') !!}
          
          <button class="btn btn-danger" type="submit">Eliminar</button>


        </form>
      </td>
     

    </tr>

    @endforeach
</tbody>
</table>
</div>
</div>
@endsection

resources/views/admin/indexHotels.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Direccion</th>
      <th scope="col">Pagina web</th>
 
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($hotels as $hotel)

    <tr>
      <td>{{$hotel->hotel_name}}</td>
      <td>{{$hotel->hotel_address}}</td>
      <td>{{$hotel->web_page}}</td>
  
      <td>
        <a class="btn btn-info btn-xs" href="{{route('hotels.edit',$hotel->id)}}">Editar</a>

        <form style="display:inline" method="POST" action="{{route('hotels.destroy',$hotel->id)}}">
          {!! csrf_field() !!}
          {!! method_field('DELETE') !!}
          
          <button class="btn btn-danger" type="submit">Eliminar</button>


        </form>
      </td>



    </tr>

    @endforeach
</tbody>
</table>
</div>
</div>
@endsection

resources/views/admin/indexServices.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Icono</th>
      <th scope="col">Acciones</th>
      
    </tr>
  </thead>
  <tbody>
  	@foreach($services as $service)

    <tr>
      <td>{{$service->service_name}}</td>
      <td>{{$service->service_description}}</td>
       <td><img src="/montpellier/storage/app/{{($service->service_icon)}}"></td>

          <td>
        <a class="btn btn-info btn-xs" href="{{route('services.edit',$service->id)}}">Editar</a>

        <form style="display:inline" method="POST" action="{{route('services.destroy',$service->id)}}">
          {!! csrf_field() !!}
          {!! method_field('DELETE') !!}
          
          <button class="btn btn-danger" type="submit">Eliminar</button>


        </form>
      </td>
     

    </tr>

    @endforeach
</tbody>
</table>
</div>
</div>
@endsection

resources/views/admin/indexUsers.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido Paterno</th>
      <th scope="col">Apellido MAterno</th>
      <th scope="col">Correo</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($users as $user)

    <tr>
      <td>{{$user->name}}</td>
  <td>{{$user->last_name}}</td>
  <td>{{$user->second_surname}}</td>
  <td>{{$user->email}}</td>

            <td>
        <a class="btn btn-info btn-xs" href="{{route('users.edit',$user->id)}}">Editar</a>

        <form style="display:inline" method="POST" action="{{route('users.destroy',$user->id)}}">
          {!! csrf_field() !!}
          {!! method_field('DELETE') !!}
          
          <button class="btn btn-danger" type="submit">Eliminar</button>


        </form>
      </td>
  
    </tr>

    @endforeach
</tbody>
</table>
</div>
</div>
@endsection

resources/views/admin/serviceEdit.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Actualizacion de Servicios de Servicios') }}</div>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('services.update',$service->id) }}">
                            {!! csrf_field() !!}
          {!! method_field('PUT') !!}

                        <div class="form-group row">
                            <label for="service_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre de la Servicio') }}</label>

                            <div class="col-md-6">
                                <input id="service_name" type="text" class="form-control{{ $errors->has('service_name') ? ' is-invalid' : '' }}" name="service_name" value="{{ $service->service_name }}" required autofocus>

                                @if ($errors->has('service_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('service_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="service_description" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion') }}</label>

                            <div class="col-md-6">
                                <input id="service_description" type="text" class="form-control" name="service_description" value="{{$service->service_description}}" required>
                            </div>
                        </div>


  						<div class="form-group row">
                            <label for="service_icon" class="col-md-4 col-form-label text-md-right">{{ __('Icono') }}</label>

                            <div class="col-md-6">
                                <input type="file" id="service_icon" type="text" class="form-control" name="service_icon" >
                            </div>
                        </div>


              



             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/serviceForm.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de Servicios') }}</div>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('services.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="service_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre de la Servicio') }}</label>

                            <div class="col-md-6">
                                <input id="service_name" type="text" class="form-control{{ $errors->has('service_name') ? ' is-invalid' : '' }}" name="service_name" value="{{ old('service_name') }}" required autofocus>

                                @if ($errors->has('service_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('service_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="service_description" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion') }}</label>

                            <div class="col-md-6">
                                <input id="service_description" type="text" class="form-control" name="service_description" required>
                            </div>
                        </div>


  						<div class="form-group row">
                            <label for="service_icon" class="col-md-4 col-form-label text-md-right">{{ __('Icono') }}</label>

                            <div class="col-md-6">
                                <input type="file" id="service_icon" type="text" class="form-control" name="service_icon" required>
                            </div>
                        </div>


              



             			<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Guardar') }}
                                </button>
                            </div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection